package.json
src/Footer.js
src/HomePage/Home.js
src/HomePage/_home.scss
src/Menubar.js
src/PlayPage/Play.js
src/PlayPage/_play.scss
src/_footer.scss
src/_menubar.scss
src/styles.scss
yarn.lock

[SWL-02] Home page revision, add mobile responsive on play page

---

src/App.js
src/ResultPage/Result.js
src/ResultPage/_result.scss
src/questions.json

Revise Brands:
- Remove Alienware brand karna itu masih termasuk kategori DELL
- Remove Apple Brand karna kita belom support Apple laptops
- Add AVITA brand for low budget users
- Add Toshiba brand for low budget users
Allow Icons:
- Dulu, stiap kali kta mau add new icons ke FE, kta harus declare iconsnya dulu di app.js. Tapi sekarang, kta udah ga perlu pusingin gituan lagi karna smua free iconsnya akan di load dulu sama FE on startup.
Ini ngebantu banget buat insights feature karna di insights feature, icon2 nya itu dynamic dari BE.
Add Insights Feature:
- Results page sekarang bisa ngehandle response baru dari BE yang akan ngereturn insights JSON.
```
"insights": {}
```
- Insights yang positive warnanya green, while yang negative warnanya red.
- **Layout between insights list dan tombol …

[ALD-02] Add Insights Feature; Allow more icons to be used; Revise brands

---

src/ResultPage/Result.js
src/ResultPage/_result.scss

/results calls localhost instead of the appropriate BE API, need to quickly fix

[ALD-04] Fix BE API route and modify layout a bit

---

src/ResultPage/Result.js
src/ResultPage/_result.scss
src/_menubar.scss

[SWL-04] Refactoring mobile screen result page, smaller insights list, smaller menubar

---

src/HomePage/Home.js
src/HomePage/_home.scss
src/ResultPage/Result.js
src/ResultPage/_result.scss
src/questions.json
src/styles.scss

**Description:**
Kita mau pindahin Promo dan WA button ke homepage biar makin banyak users yang dateng
Kita juga ngerubah pertanyaan soal laptop size buat kasih lebih banyak opsi buat users
**Test:**

[ALD-06] Move WA Float and Promo to homepage ; Change laptop size question

---

src/App.js
src/DecryptPage/Decrypt.js
src/HomePage/Home.js
src/ResultPage/Result.js
src/components/HeadlineHighlight.js

Nnti bru gw kerjain ya descnya...

[ALD-07] Fix code smell; attempt to fix iphone layout issue

---

src/HomePage/Home.js
src/HomePage/_home.scss
src/_footer.scss

- Change partnership name jadi partnership affiliate biar kta ga kena masalah
- Change footer color biar lebih seragam
- Align IMG Jumbotron
- Change HIW to have add to cart
- Screenshot skipped karna buru2

[ALD-08] Change partner name ; footer color ; align jumbotron img ; change add to cart

---

src/Footer.js

Kita mau ngerubah email yang di footer jadi khusus buat propicks.
Sayangnya, kalau kta bkin email ...@propicks.id, bayarnya lmayan cuy, karena itu ga penting2 amat, ya kta pake email biasa dulu aja ya

[ALD-09] Change email to propicks gmail

---

src/PlayPage/Play.js
src/PlayPage/_play.scss
src/questions.json

**Description:**
Refactoring play page jadi functional component agar mudah di maintenance ke depannya, menambahkan icon ke option-multiple agar dapat dibedakan antara option-single dan option-multiple.
**Test:**
Small Laptop
Large Laptop
Mobile Screen

[SWL-06] Refactoring play page, add icon for multiple option

---

src/questions.json

Langsung dimerge aja lah ya ga perlu explanation

[ALD-10] Add extra questions for custom slider

---

src/ResultPage/Result.js
src/ResultPage/_result.scss
src/questions.json

Ada beberapa empty space yang ga kepake di result (mobile screen), jadi kta optimize lagi aja spacingnya

[ALD-10] Change margin on mobile screen a bit to make up more space

---

src/ResultPage/Result.js
src/ResultPage/_result.scss
src/questions.json

- Kta smpet dikomplen beberapa use r karna pertanyaan soal img graphics tuh aneh, kenapa masih ada opsi "sya tidak melakukan image editing" gtu. Dan stelah dicek, itu bsa diremove sih.
- Revise pilihan di question brand juga karna orang suka ga nyadar kalau mreka ada pilihan buat ga pilih brand

[ALD-10] Revise questions based on user  feedback

---

public/index.html

**Description**
- Kita mau taro Tiktok Ad Manager to measure conversions
**Test:**
- Yarn start berjalan mulus

[ALD-12] Add Tiktok Tag Manager

---

src/PlayPage/Play.js
src/PlayPage/_play.scss
src/_footer.scss
src/styles.scss

Redesign quiz page dengan menambahkan header introduction dan footer, menambah empty circle icon untuk multiple option, mengganti warna biru dan hijau jadi lebih soft.
Laptop Large Screen (1920px - 1080px)
Laptop Small Screen (1366px - 768px)
Mobile Screen Iphone SE (375px - 667px)

[SWL-09] Redesign quiz page, add header and footer

---

public/index.html

Kita mau konekin propicks ke google adsense biar kta bsa taro ads on it
- Page still runs well in local

[ALD-13] Add Google Adsense Tag

---

README.md
package-lock.json
package.json
src/ResultPage/Result.js
src/ResultPage/_result.scss
src/questions.json
yarn.lock

Membuat Carousel Slider Image untuk multiple image/image laptop lebih dari satu di result page. Sudah bisa di dragging atau touch slide saat di mobile screen.
Laptop Large Screen (1920px - 1080px)
Laptop Small Screen (1366px - 768px)
Mobile Screen Iphone SE (375px - 667px)

[SWL-11] make simple carousel image for multiple image laptop

---

src/Footer.js
src/ResultPage/Result.js
yarn.lock

Google adsense bilang kalau website kita itu ga ada kontennya dan under construction, Jadi gw create 2 fi
- Remove link "kontak kami" di footer karna kta emg blm ada contact us page
- Kalau crawlernya access "/result" page directly, previously tuh kta ga bakal return any data. Tapi skrg kta akan return dummy data
- Local test Berhasil
Note -- gw nyadar ide yang dummy result ini agak bodoh, tapi ini mau ngetest google adsense approvalnya dulu

[ALD-14] Remove non-complete links; Add dummy call for cases where user/crawler access result page directly

---

src/Footer.js
src/HomePage/Home.js
src/ResultPage/Result.js
yarn.lock

User pada kira kalau konsultasi itu bayar, jadi kta ganti wordingnya

[ALD-14] Ganti wording untuk konsultasi

---

src/HomePage/Home.js
src/HomePage/_home.scss

- Gw notice kalau banyak user yang ga sadar kalau mreka itu perlu kerjain quiznya buat dapetin rekomendasi laptop, jadi sub headlinenya perlu diubah
- Locally Tested

[ALD-18] Change Sub headline biar lebih jelas

---

public/index.html
src/HomePage/Home.js
src/HomePage/_home.scss
src/ResultPage/Result.js

Kita tambahin Google Tag Manager code snippet karna mau negtest GTM buat Sponsorship
Local Test

[ALD-19] Add Google Tag Manager

---

src/LaptopDetailsPage/_laptopDetails.scss
src/components/result/LaptopList.js
src/components/result/_laptopList.scss

- Remove codesmell dari sonarcloud
- Sponsored laptops hrus pnya top border
- Tebelin border orange
- Alasan feature should only be for sponsored laptops

[ALD-21] Remove duplicate css, alasan feature cmn buat sponsored laptops ; sponsored laptops get top border

---

src/components/result/LaptopList.js

- We want to add extra class for sponsored button so that we can use it for google tracking
- Local Test

[ALD-22] Add extra class for sponsored button

---

src/components/result/LaptopList.js
src/components/result/_laptopList.scss

- Kata orang2, trusted partnernya kurang keliatan, jadi kita perlu gedein.
- Dan steleah digedein, kykny bgusan background and shadownya diilangin deh

[ALD-22] Improve Trusted Partner

---

src/components/FeedbackModal.js

Feedback Modal itu ada bug, messagenya dari user itu ga kekirim. Jadi perlu di fix
Local test masih berjalan. dan feedback juga udah ke store di DB

[ALD-23] Resolve bug on feedback modal

---

src/PlayPage/Play.js
src/questions.json

We want to add touchscreen question biar kita punya touchscreen feature

[ALD-25] Add Touchscreen question
